# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectAdminregister',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(max_length=30)),
                ('a_pwd', models.CharField(max_length=30)),
                ('a_sex', models.CharField(max_length=5)),
                ('a_number', models.CharField(max_length=20)),
                ('a_phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mainproject_adminregister',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectAuthors',
            fields=[
                ('au_id', models.AutoField(primary_key=True, serialize=False)),
                ('au_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mainproject_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectBooks',
            fields=[
                ('bk_id', models.AutoField(primary_key=True, serialize=False)),
                ('bk_name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('intro', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mainproject_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectBooktype',
            fields=[
                ('bt_id', models.AutoField(primary_key=True, serialize=False)),
                ('bt_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mainproject_booktype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectBorrowBooks',
            fields=[
                ('bb_id', models.AutoField(primary_key=True, serialize=False)),
                ('bb_bdate', models.DateField()),
                ('bb_rdate', models.DateField()),
            ],
            options={
                'db_table': 'mainproject_borrow_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectBorrowPersons',
            fields=[
                ('bp_id', models.AutoField(primary_key=True, serialize=False)),
                ('bp_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mainproject_borrow_persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectBorrowPersonsBpBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'mainproject_borrow_persons_bp_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectPress',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mainproject_press',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectProfessions',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mainproject_professions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainprojectUserregister',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=30)),
                ('usex', models.CharField(max_length=5)),
                ('unumber', models.CharField(max_length=20)),
                ('uphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'mainproject_userregister',
                'managed': False,
            },
        ),
    ]
